### ISSUE TITLE
Module not found: Error: Cannot resolve module 'style'

### ISSUE THREAD

**Issue by mackxu** [supnate/react-tab-selector#1]
ERROR in ./js/app.js
Module not found: Error: Cannot resolve module 'style'

**Comment by Pana** [comment]
This seems lack the ""style-loader", but when i install the loader i got an new error 

```
Module not found: Error: Cannot resolve module 'css'
```

**Comment by Pana** [comment]
I have figure it out, you also need to install "css-loader"

**Comment by supnate** [comment]
Thank you @Pana ! The issue has been fixed.
