### ISSUE TITLE
热更无效

### ISSUE THREAD

**Issue by wait-hua** [supnate/react-tab-selector#2]
你好，按照您的步骤：
Run npm install then npm start:
http://localhost:3000/tab_selector_hot_loader.html
启动起来了，但是我更改app.js里的data值，热更无效报错：
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)

但是更改style.css里的样式就可以热更。是哪里要配置吗？

**Comment by supnate** [comment]
HMR（Hot module replacement）是有限制的，不是所有改动都可以热更。比如某个已经显示的组件的构造函数。遇到这种情况，Webpack就会有问题中的提示：
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
即此时必须刷新页面才能生效。app.js里的data就是这种情况，无法热更新。

一般所有样式文件、组件上的方法、事件处理函数、render方法，这些都是能正常热更。

**Comment by Shiyanping** [comment]
不知道为什么热更一会好使一会不好使，而且jsx里面修改了需要刷新页面
